In [99]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import utils

In [100]:
url = 'https://raw.githubusercontent.com/sambuddharay/FinalYearProject/main/scrapping/data/Premier-League-Stats/2022-2023/player/Premier-League-Stats-2022-2023-defense-player.csv'
df1 = pd.read_csv(url)
url = 'https://raw.githubusercontent.com/sambuddharay/FinalYearProject/main/scrapping/data/Premier-League-Stats/2022-2023/player/Premier-League-Stats-2022-2023-gca-player.csv'
df2 = pd.read_csv(url)
url = 'https://raw.githubusercontent.com/sambuddharay/FinalYearProject/main/scrapping/data/Premier-League-Stats/2022-2023/player/Premier-League-Stats-2022-2023-misc-player.csv'
df3 = pd.read_csv(url)
url = 'https://raw.githubusercontent.com/sambuddharay/FinalYearProject/main/scrapping/data/Premier-League-Stats/2022-2023/player/Premier-League-Stats-2022-2023-passing-player.csv'
df4 = pd.read_csv(url)
url = 'https://raw.githubusercontent.com/sambuddharay/FinalYearProject/main/scrapping/data/Premier-League-Stats/2022-2023/player/Premier-League-Stats-2022-2023-possession-player.csv'
df5 = pd.read_csv(url)
url = 'https://raw.githubusercontent.com/sambuddharay/FinalYearProject/main/scrapping/data/Premier-League-Stats/2022-2023/player/Premier-League-Stats-2022-2023-shooting-player.csv'
df6 = pd.read_csv(url)

In [101]:
frames = [df1[['Player', 'Nation', 'Pos', 'Squad', 'Born', '90s', 'Tackles Tkl', 'Tackles TklW', 'Tackles Def 3rd', 'Tackles Mid 3rd', 'Tackles Att 3rd', 'Challenges Tkl', 'Challenges Att', 'Challenges Lost', 'Blocks Blocks', 'Blocks Sh', 'Blocks Pass', 'Int', 'Tkl+Int', 'Clr', 'Err']],
          df2[['SCA SCA', 'SCA SCA90', 'SCA Types PassLive', 'SCA Types PassDead', 'SCA Types TO', 'SCA Types Sh', 'SCA Types Fld', 'SCA Types Def', 'GCA GCA', 'GCA GCA90', 'GCA Types PassLive', 'GCA Types PassDead', 'GCA Types TO', 'GCA Types Sh', 'GCA Types Fld', 'GCA Types Def']],
          df3[['Performance CrdY', 'Performance CrdR', 'Performance 2CrdY', 'Performance Fls', 'Performance Fld', 'Performance Off', 'Performance Crs', 'Performance Int', 'Performance TklW', 'Performance PKwon', 'Performance PKcon', 'Performance OG', 'Performance Recov', 'Aerial Duels Won', 'Aerial Duels Lost']],
          df4[['Total Cmp', 'Total Att', 'Total Cmp%', 'Total TotDist', 'Total PrgDist', 'Short Cmp', 'Short Att', 'Medium Cmp', 'Medium Att', 'Long Cmp', 'Long Att', 'Ast', 'xAG', 'Expected xA', 'Expected A-xAG', 'KP', '1/3', 'PPA', 'CrsPA', 'PrgP']],
          df5[['Touches Touches', 'Touches Def Pen', 'Touches Def 3rd', 'Touches Mid 3rd', 'Touches Att 3rd', 'Touches Att Pen', 'Touches Live', 'Take-Ons Att', 'Take-Ons Succ', 'Take-Ons Tkld', 'Carries Carries', 'Carries TotDist', 'Carries PrgDist', 'Carries PrgC', 'Carries 1/3', 'Carries CPA', 'Carries Mis', 'Carries Dis', 'Receiving Rec', 'Receiving PrgR']],
          df6[['Standard Gls', 'Standard Sh', 'Standard SoT','Standard Sh/90', 'Standard SoT/90', 'Standard G/Sh', 'Standard G/SoT', 'Standard Dist', 'Standard FK', 'Standard PK', 'Standard PKatt', 'Expected xG', 'Expected npxG', 'Expected npxG/Sh', 'Expected G-xG', 'Expected np:G-xG']]]
players = pd.concat(frames, axis=1)

In [102]:
url = 'https://raw.githubusercontent.com/sambuddharay/FinalYearProject/main/scrapping/data/Premier-League-Stats/2022-2023/player/Premier-League-Stats-2022-2023-keepers-player.csv'
df7 = pd.read_csv(url)
url = 'https://raw.githubusercontent.com/sambuddharay/FinalYearProject/main/scrapping/data/Premier-League-Stats/2022-2023/player/Premier-League-Stats-2022-2023-keepersadv-player.csv'
df8 = pd.read_csv(url)

In [103]:
df7=df7[df7['Playing Time 90s']>0]
df8=df8[df8['90s']>0]
frames = [df7[['Player', 'Performance GA', 'Performance GA90', 'Performance SoTA', 'Performance Saves', 'Performance Save%', 'Performance W', 'Performance D', 'Performance L', 'Performance CS', 'Performance CS%', 'Penalty Kicks PKatt', 'Penalty Kicks PKA', 'Penalty Kicks PKsv', 'Penalty Kicks PKm']],
          df8[['Goals GA', 'Goals PKA', 'Goals FK', 'Goals CK', 'Goals OG', 'Expected PSxG', 'Expected PSxG/SoT', 'Expected PSxG+/-', 'Expected /90', 'Launched Cmp', 'Launched Att', 'Launched Cmp%', 'Passes Att (GK)', 'Passes Thr', 'Passes Launch%', 'Passes AvgLen', 'Goal Kicks Att', 'Goal Kicks Launch%', 'Goal Kicks AvgLen', 'Crosses Opp', 'Crosses Stp', 'Crosses Stp%', 'Sweeper #OPA', 'Sweeper #OPA/90', 'Sweeper AvgDist']]]
goalkeepers = pd.concat(frames, axis=1)

In [104]:
players = players.replace(np.nan, 0)
goalkeepers = goalkeepers.replace(np.nan, 0)

In [105]:
players.tail()

,Player,Nation,Pos,Squad,Born,90s,Tackles Tkl,Tackles TklW,Tackles Def 3rd,Tackles Mid 3rd,...,Standard G/SoT,Standard Dist,Standard FK,Standard PK,Standard PKatt,Expected xG,Expected npxG,Expected npxG/Sh,Expected G-xG,Expected np:G-xG
564,Jordan Zemura,ZIM,DF,Bournemouth,1999,16.2,39,24,24,14,...,0.00,12.9,0,0,0,0.4,0.4,0.10,-0.4,-0.4
565,Oleksandr Zinchenko,UKR,DF,Arsenal,1996,23.5,40,18,14,17,...,0.14,22.7,0,0,0,1.4,1.4,0.05,-0.4,-0.4
566,Hakim Ziyech,MAR,FW|MF,Chelsea,1993,7.3,20,12,12,5,...,0.00,22.7,0,0,0,0.6,0.6,0.04,-0.6,-0.6
567,Kurt Zouma,FRA,DF,West Ham,1994,22.1,9,4,4,5,...,0.40,10.1,0,0,0,2.2,2.2,0.12,-0.2,-0.2
568,Martin Ødegaard,NOR,MF,Arsenal,1998,34.7,36,23,12,14,...,0.48,19.2,9,0,0,10.0,10.0,0.11,5.0,5.0

In [106]:
players = players[players['90s']>0]

In [107]:
players.shape

(558, 108)

In [108]:
players = players.replace(np.nan, 0)
goalkeepers = goalkeepers.replace(np.nan, 0)
players_compiled = players.merge(goalkeepers, how='left')
players_compiled = players_compiled.replace(np.nan, 0)

In [109]:
cat_info = players_compiled[['Player', 'Nation', 'Pos', 'Squad', 'Born']]
players_compiled = players_compiled.drop(columns=['Player', 'Nation', 'Pos', 'Squad', 'Born'])

In [110]:
# Convert each row of the DataFrame into a NumPy matrix
player_matrices = [row.to_numpy() for index, row in players_compiled.iterrows()]

# Convert the list of matrices into a NumPy array
player_matrices_array = np.array(player_matrices)

player_matrices_array

array([[26.4, 45. , 18. , ...,  0. ,  0. ,  0. ],
       [22.1, 17. , 13. , ...,  0. ,  0. ,  0. ],
       [24. , 89. , 46. , ...,  0. ,  0. ,  0. ],
       ...,
       [ 7.3, 20. , 12. , ...,  0. ,  0. ,  0. ],
       [22.1,  9. ,  4. , ...,  0. ,  0. ,  0. ],
       [34.7, 36. , 23. , ...,  0. ,  0. ,  0. ]])

In [111]:
player_matrices_array.shape

(558, 142)

In [112]:
player_matrices_array = player_matrices_array.reshape(558,1,142)
player_matrices_array

array([[[26.4, 45. , 18. , ...,  0. ,  0. ,  0. ]],

       [[22.1, 17. , 13. , ...,  0. ,  0. ,  0. ]],

       [[24. , 89. , 46. , ...,  0. ,  0. ,  0. ]],

       ...,

       [[ 7.3, 20. , 12. , ...,  0. ,  0. ,  0. ]],

       [[22.1,  9. ,  4. , ...,  0. ,  0. ,  0. ]],

       [[34.7, 36. , 23. , ...,  0. ,  0. ,  0. ]]])

In [113]:
player_matrices_array.shape

(558, 1, 142)

In [114]:
loss_df = pd.read_csv('https://raw.githubusercontent.com/sambuddharay/FinalYearProject/main/cnn/loss_data.csv')

In [115]:
# Sort the DataFrame based on the absolute values of the 'Loss' column
df_sorted = loss_df.assign(Abs_Loss=loss_df['Loss'].abs()).sort_values(by='Abs_Loss')

# Extract the feature indexes of the 36 features with lowest loss
feature_indexes_lowest_loss = df_sorted.head(36)['Feature Index'].tolist()

# Print the feature indexes
feature_indexes_lowest_loss

[29,
 91,
 0,
 2,
 89,
 111,
 7,
 100,
 121,
 117,
 65,
 58,
 122,
 62,
 45,
 1,
 34,
 17,
 20,
 113,
 43,
 37,
 70,
 75,
 129,
 63,
 72,
 123,
 35,
 18,
 136,
 119,
 128,
 110,
 86,
 139]

In [116]:
# Convert the list of feature indexes to NumPy array
feature_indexes_lowest_loss = np.array(feature_indexes_lowest_loss)

# Delete the selected features from X_train
X_train_filtered = np.delete(player_matrices_array, feature_indexes_lowest_loss, axis=2)

# Check the new shape of X_train_filtered
X_train_filtered.shape

(558, 1, 106)

In [117]:
from keras.models import load_model

# Load the model
model = load_model("mymodel.keras")

In [118]:
X_train_filtered = np.pad(X_train_filtered, ((0, 0), (0, 59), (0, 0)), mode='constant')
X_train_filtered.shape

(558, 60, 106)

In [119]:
predictions = model.predict(X_train_filtered)

18/18 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step

In [120]:
predictions.shape

(558, 1)

In [121]:
df2 = pd.DataFrame(predictions, columns=['Score'])
player_score = pd.concat([cat_info, df2], axis=1)
player_score

                  Player Nation    Pos         Squad  Born       Score
0       Brenden Aaronson    USA  MF|FW  Leeds United  2000   71.969116
1              Che Adams    SCO     FW   Southampton  1996   38.966030
2            Tyler Adams    USA     MF  Leeds United  1999  134.449371
3       Tosin Adarabioyo    ENG     DF        Fulham  1997  114.527199
4           Nayef Aguerd    MAR     DF      West Ham  1996   53.048378
..                   ...    ...    ...           ...   ...         ...
553        Jordan Zemura    ZIM     DF   Bournemouth  1999   25.075788
554  Oleksandr Zinchenko    UKR     DF       Arsenal  1996  196.584488
555         Hakim Ziyech    MAR  FW|MF       Chelsea  1993   29.897823
556           Kurt Zouma    FRA     DF      West Ham  1994   78.047890
557      Martin Ødegaard    NOR     MF       Arsenal  1998  185.593903

[558 rows x 6 columns]

In [122]:
sorted_df = player_score.sort_values(by='Score', ascending=False)
sorted_df.head(30)

                     Player Nation    Pos            Squad  Born       Score
428                   Rodri    ESP     MF  Manchester City  1996  334.824066
509         Kieran Trippier    ENG     DF    Newcastle Utd  1990  324.282318
13   Trent Alexander-Arnold    ENG     DF        Liverpool  1998  295.089630
515         Virgil van Dijk    NED     DF        Liverpool  1991  289.743530
148              Lewis Dunk    ENG     DF         Brighton  1991  278.920898
231         Pierre Højbjerg    DEN     MF        Tottenham  1995  254.432358
204           Jack Grealish    ENG     FW  Manchester City  1995  254.083328
366             Rúben Neves    POR     MF           Wolves  1997  245.440002
529       James Ward-Prowse    ENG     MF      Southampton  1994  242.440186
348            Kaoru Mitoma    JPN  FW|MF         Brighton  1997  238.089584
418             Declan Rice    ENG     MF         West Ham  1999  232.473007
440             Bukayo Saka    ENG     FW          Arsenal  2001  230.643463
73           Moisés Caicedo    ECU     MF         Brighton  2001  229.311020
206             Pascal Groß    GER  MF|DF         Brighton  1991  226.418762
534               Ben White    ENG     DF          Arsenal  1997  224.951675
423        Andrew Robertson    SCO     DF        Liverpool  1994  218.637299
390           Thomas Partey    GHA     MF          Arsenal  1993  206.093262
209              Marc Guéhi    ENG     DF   Crystal Palace  2000  204.992661
140      Gabriel Dos Santos    BRA     DF          Arsenal  1997  201.977661
524             Kyle Walker    ENG     DF  Manchester City  1990  200.024628
303            Douglas Luiz    BRA     MF      Aston Villa  1998  199.901810
554     Oleksandr Zinchenko    UKR     DF          Arsenal  1996  196.584488
164                 Fabinho    BRA     MF        Liverpool  1993  194.134399
306     Alexis Mac Allister    ARG     MF         Brighton  1998  191.908508
8             Manuel Akanji    SUI     DF  Manchester City  1995  191.459579
169         Bruno Fernandes    POR  MF|FW   Manchester Utd  1994  186.255310
557         Martin Ødegaard    NOR     MF          Arsenal  1998  185.593903
19         Joachim Andersen    DEN     DF   Crystal Palace  1996  183.177612
415                Tim Ream    USA     DF           Fulham  1987  182.188339
62              Sven Botman    NED     DF    Newcastle Utd  2000  177.625885

In [123]:
sorted_df.tail(30)

                   Player Nation    Pos            Squad  Born     Score
212           Darko Gyabi    ENG     FW     Leeds United  2004  0.106144
67            Lewis Brunt    ENG     DF   Leicester City  2000  0.094175
15              Dele Alli    ENG     MF          Everton  1996  0.081197
342           Lewis Miley    ENG     MF    Newcastle Utd  2006  0.018181
318    Emiliano Marcondes    DEN     MF      Bournemouth  1995 -0.000782
296  Valentino Livramento    ENG  DF|FW      Southampton  2002 -0.028450
109         Matthew Craig    SCO     MF        Tottenham  2003 -0.055317
449         Morgan Sanson    FRA     MF      Aston Villa  1994 -0.068665
72                   Cafú    POR     MF  Nott'ham Forest  1993 -0.213053
144            Kami Doyle    ENG     MF      Southampton  2005 -0.258076
79          Thomas Cannon    IRL     FW          Everton  2002 -0.283861
258        Sasa Kalajdzic    AUT     FW           Wolves  1997 -0.287494
230      Omari Hutchinson    ENG     FW          Chelsea  2003 -0.413747
514            Yan Valery    TUN     DF      Southampton  1999 -0.456683
535          Harvey White    ENG     MF        Tottenham  2001 -0.486647
291           Jamal Lewis    NIR  DF|FW    Newcastle Utd  1998 -0.497410
138              Ben Doak    SCO     FW        Liverpool  2005 -0.523208
479           Djed Spence    ENG  FW|DF        Tottenham  2000 -0.543246
302            Jamal Lowe    JAM  MF|FW      Bournemouth  1994 -0.548124
351          Andrew Moran    IRL     FW         Brighton  2003 -0.661804
215           Luke Harris    WAL  MF|FW           Fulham  2005 -0.666892
47     Mads Bech Sørensen    DEN  DF|MF        Brentford  1999 -0.674561
57             Owen Bevan    WAL     DF      Bournemouth  2003 -0.678225
482        Jay Stansfield    ENG     FW           Fulham  2002 -0.759311
409           Isaac Price    NIR     MF          Everton  2003 -0.873051
400       Cameron Peupion    AUS     MF         Brighton  2002 -1.154340
253          Mateo Joseph    ENG  FW|MF     Leeds United  2003 -1.268042
382          Mislav Oršić    CRO     MF      Southampton  1992 -1.562229
95            Bobby Clark    ENG     MF        Liverpool  2005 -1.746874
341          Alex Mighten    ENG     FW  Nott'ham Forest  2002 -3.805836